name: release
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gryphonshafer/GitHub-MD-Book@v3
        with:
          settings: .github/github-md-book.yml
