# This is a basic workflow to help you get started with Actions

name: Release Book

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build GitHub MD Book
        uses: gryphonshafer/GitHub-MD-Book@v3
        with:
        # Build configuration settings YAML file repository location
          settings:
            .github/github-md-book.yml
            

      # Runs a single command using the runners shell
      - name: Release
      - env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |-
          set -x
          assets=()
          for asset in ./output/*
          do
            assets+=("-a" "$asset")
          done
          now=$( date '+%Y-%m-%d %H:%M:%S %Z' )
          time=$( date '+%s' )
          branch=$( echo ${GITHUB_REF} | cut -c12-100 )
          [[ ${branch} == 'master' ]] && p="" || p="--prerelease"
          echo $GITHUB_TOKEN
          wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar xvfpz hub-linux-amd64-2.14.2.tgz
          ./hub-linux-amd64-2.14.2/bin/hub release create "${assets[@]}" $p -m "$now - $branch" "$time"

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
